[project]
name = "Melon"
dynamic = ["version"]
dependencies = [
	"beautifulsoup4",
	"EbookLib",
	"dulwich>=1.2.6",
	"dublib==0.28.2",
	"pillow",
]

[project.optional-dependencies]
dev = [
	"mypy",
	"ruff"
]

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
non_interactive = true
follow_imports = "silent"
files = [
	"main.py",
	"Source"
]
exclude = [
	"Source/CLI/Legacy",
	"Source/Core/Base/Builders",
	"Source/Core/Base/Parsers/Components/ChapterHeaderParser",
	"Source/Utils/Development.py",
	"__pycache__"
]

[tool.ruff]
include = [
	"main.py",
	"Source"
]
exclude = [
	"Source/CLI/Legacy",
	"Source/Core/Base/Builders",
	"Source/Core/Base/Parsers/Components/ChapterHeaderParser",
	"Source/Utils/Development.py",
	"__pycache__"
]

[tool.ruff.lint]
ignore = ["E701"]