[project]
name = "Melon"
dynamic = ["version"]
dependencies = [
	"beautifulsoup4",
	"dublib==0.28.5",
	"dulwich>=1.2.6",
	"EbookLib",
	"img2pdf",
	"pillow"
]

[project.optional-dependencies]
dev = [
	"mypy",
	"ruff"
]

[tool.setuptools.packages.find]
include = ["Source*"]

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
non_interactive = true
follow_imports = "silent"
files = [
	"main.py",
	"Source"
]
exclude = [
	"__pycache__"
]

[tool.ruff]
include = [
	"main.py",
	"Source"
]
exclude = [
	"__pycache__"
]

[tool.ruff.lint]
ignore = ["E701"]