[build-system]
requires = ["uv-build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[project]
name = "melon"
version = "1.0.0-rc.6"
description = "Modular parsers management system."
readme = "README.md"
authors = [
    { name = "DUB1401", email = "vlad.milosta@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
	"beautifulsoup4",
	"dublib>=0.31.1",
	"dulwich>=1.2.6",
	"EbookLib",
	"imagehash",
	"img2pdf",
	"opencv-python-headless",
	"pick",
	"pillow",
	"python-dotenv",
	"uv"
]

[project.optional-dependencies]
dev = ["ruff", "ty", "typos"]

[project.scripts]
melon = "melon:main"
pxm = "melon:main"
urun = "melon:main"

[tool.ruff.lint]
select = ["A", "ARG", "C", "E", "F", "I", "TC", "UP"]
ignore = ["C901", "E701", "E501"]

[tool.ruff.lint.isort]
lines-after-imports = 1
sections = {"dublib" = ["dublib"], "melon" = ["melon"]}
section-order = [
	"future",
	"standard-library",
	"third-party",
	"dublib",
	"melon",
	"first-party",
	"local-folder"
]

[tool.typos.default.extend-words]
sigen = "sigen" # Short for signature generator.
