from dublib.CLI.Terminalyzer import Command, ParametersTypes
from dublib.CLI.TextStyler.FastStyler import FastStyler

CommandsList: list[Command] = list()

Com = Command("build-manga", "Build readable manga.")
ComPos = Com.create_position("SOURCE", "Title's data.", important = True)
ComPos.add_argument(description = "Filename of local JSON.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Alpha, "Parser name.")
ComPos = Com.create_position("TARGET", "Target for building.")
ComPos.add_key("branch", ParametersTypes.Number, "Branch ID.")
ComPos.add_key("chapter", ParametersTypes.Number, "Chapter ID.")
ComPos = Com.create_position("BUILDER", "Type of building system.")
ComPos.add_flag("simple", "Download images in directories (default).")
ComPos.add_flag("zip", "Make *.ZIP archives.")
ComPos.add_flag("cbz", "Make *.CBZ files.")
Com.base.add_key("ch-template", description = "Template for chapters naming. Available {number} and {name} replacements.")
Com.base.add_key("vol-template", description = "Template for volumes naming. Available {number} replacement.")
Com.base.add_flag("v", description = "Enable chapters sorting by volumes directories.")
CommandsList.append(Com)

Com = Command("build-ranobe", "Build readable ranobe.")
ComPos = Com.create_position("SOURCE", "Title's data.", important = True)
ComPos.add_argument(description = "Filename of local JSON.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Alpha, "Parser name.")
ComPos = Com.create_position("TARGET", "Target for building.")
ComPos.add_key("branch", ParametersTypes.Number, "Branch ID.")
CommandsList.append(Com)

Com = Command("cacher", "Cache ID-slugs pairs for file searching speed increase in all parsers by default.")
ComPos = Com.create_position("PARSERS", "List of parsers names to caching.")
ComPos.add_key("use", description = "One or more parsers names separated by comma.")
CommandsList.append(Com)

CollectionFileBold = FastStyler("Collection.txt").decorate.italic
Com = Command("collect", f"Collect titles slugs into {CollectionFileBold} file.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Alpha, "Parser name.")
Com.base.add_flag("f", "Enable force mode.")
Com.base.add_flag("local", "Scan local titles and put into collection.")
Com.base.add_flag("no-sort", "Disable slugs sorting.")
Com.base.add_key("filters", description = "Query string for filtering titles (supporting optional).")
Com.base.add_key("pages", ParametersTypes.Number, "Count of pages to collecting.")
Com.base.add_key("period", ParametersTypes.Number, "Period in hours for parsing updates.")
CommandsList.append(Com)

Com = Command("fid", "Find title ID by slug in cache.")
ComPos = Com.create_position("SLUG", "Title slug.")
ComPos.add_argument()
ComPos = Com.create_position("PARSERS", "List of parsers names to searching.")
ComPos.add_key("use", description = "One or more parsers names separated by comma.")
Com.base.add_flag("all", "Print all search results instead only first.")
CommandsList.append(Com)

Com = Command("get", "Download image.")
ComPos = Com.create_position("URL", "Image source.")
ComPos.add_argument(ParametersTypes.URL, "Link to image.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Alpha, "Parser name.")
ComPos = Com.create_position("NAME", "Type of naming.")
ComPos.add_key("fullname", description = "Full name of file.")
ComPos.add_key("name", description = "Name of file without type.")
Com.base.add_flag("f", "Enable force mode.")
Com.base.add_key("dir", ParametersTypes.ValidPath, "Output directory.")
CommandsList.append(Com)

Com = Command("init", "Initialize new parser or extension directory for development.")
ComPos = Com.create_position("TYPE", "Type of module.", important = True)
ComPos.add_flag("e", "Extension.")
ComPos.add_flag("p", "Parser.")
ComPos = Com.create_position("NAME", "Parser or extension name.", important = True)
ComPos.add_argument(ParametersTypes.All, description = "Extension name.")
ComPos.add_argument(ParametersTypes.Alpha, description = "Parser name.")
ComPos = Com.create_position("CONTENT", "Parser content types.")
ComPos.add_key("content", description = "Parser content types. For example \"manga,ranobe\".")
Com.base.add_flag("f", "Enable force mode.")
Com.base.add_flag("git", "Initialize new Git repository.")
CommandsList.append(Com)

Com = Command("install", "Run installation assistant.")
Com.base.add_flag("a", "Add alias to venv activate script.")
Com.base.add_flag("c", "Copy parsers and extensions default settings in Configs if not exists.")
Com.base.add_flag("all", "Full installation.")
Com.base.add_flag("r", "Install parsers requirements (only Python packages).")
Com.base.add_flag("s", "Running parsers installation scripts.")
Com.base.add_flag("t", "Switch parsers submodules to the latest stable tag.")
Com.base.add_flag("f", "Enable force mode.")
CommandsList.append(Com)

Com = Command("list", "Print list of installed parsers.")
CommandsList.append(Com)

Com = Command("parse", "Start titles parsing.")
ComPos = Com.create_position("TARGET", "Target for parsing.", important = True)
ComPos.add_argument(description = "Title slug.")
ComPos.add_key("id", ParametersTypes.Number, "Title ID for searching slug in local files.")
ComPos.add_flag("collection", "Parse slugs from Collection.txt file.")
ComPos.add_flag("local", "Parse all locally saved titles.")
ComPos.add_flag("updates", "Parse titles updated for last 24 hours.")
ComPos.add_flag("last", "Parse last processed slug.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Alpha, "Parser name.")
Com.base.add_key("period", ParametersTypes.Number, "Period in hours for parsing. Use with -updates flag.")
Com.base.add_key("from", description = "Skip titles before this slug.")
Com.base.add_flag("f", "Enable force mode.")
Com.base.add_flag("sort", "Enable chapters sorting after parsing.")
Com.base.add_flag("no-amend", "Disable chapters content amending.")
CommandsList.append(Com)

Com = Command("repair", "Repair chapter content in locally saved title.")
ComPos = Com.create_position("FILENAME", "Source file.", important = True)
ComPos.add_argument(description = "Filename of locally saved title.")
ComPos = Com.create_position("TARGET", "Target for repairing.", important = True)
ComPos.add_key("chapter", ParametersTypes.Number, "Chapter ID.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Alpha, "Parser name.")
CommandsList.append(Com)

Com = Command("run", "Run specific modules.")
ComPos = Com.create_position("TARGET", "Target to run.", important = True)
ComPos.add_key("extension", description = "Extension full name.")
Com.base.add_flag("f", "Enable force mode.")
Com.base.add_key("command", description = "Extension command.")
CommandsList.append(Com)

Com = Command("tagger", "Process titles classificators.")
ComPos = Com.create_position("INPUT", "Input data.", important = True)
ComPos.add_key("classificator", ParametersTypes.All, "Unknown type of classificator.")
ComPos.add_key("genre", ParametersTypes.All, "Genre.")
ComPos.add_key("franchise", ParametersTypes.All, "Franchise.")
ComPos.add_key("tag", ParametersTypes.All, "Tag.")
ComPos = Com.create_position("PARSER", "Parser name to determine source rules.")
ComPos.add_key("use", ParametersTypes.Alpha, "Parser name.")
ComPos = Com.create_position("OUTPUT", "Output mode.")
ComPos.add_flag("print", "Styled print in console (default).")
ComPos.add_flag("json", "Prints JSON-string in console.")
ComPos.add_key("file", description = "Path to dump JSON file.")
CommandsList.append(Com)