from dublib.CLI.Terminalyzer import Command, ParametersTypes

CommandsList: list[Command] = list()

Com = Command("build", "Build readable content.")
ComPos = Com.create_position("FILENAME", "Source file.", important = True)
ComPos.add_argument(description = "Filename of locally saved title.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Text, "Parser name.")
Com.add_flag("cbz", "Make *.CBZ archives.")
CommandsList.append(Com)

Com = Command("collect", "Collect titles slugs into Collection.txt file.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Text, "Parser name.")
Com.add_flag("f", "Enable force mode.")
Com.add_flag("s", "Shutdown PC after script finish.")
Com.add_flag("local", "Scan local titles and put into collection.")
Com.add_flag("sort", "Enable slugs sorting.")
Com.add_key("filters", description = "Query string for filtering titles (supporting optional).")
Com.add_key("pages", ParametersTypes.Number, "Count of pages to collecting.")
Com.add_key("period", ParametersTypes.Number, "Period in hours for parsing updates.")
CommandsList.append(Com)

Com = Command("get", "Download image.")
ComPos = Com.create_position("URL", "Image source.")
ComPos.add_argument(ParametersTypes.URL, "Link to image.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Text, "Parser name.")
ComPos = Com.create_position("NAME", "Type of naming.")
ComPos.add_key("fullname", description = "Full name of file.")
ComPos.add_key("name", "Name of file without type.")
Com.add_flag("f", "Enable force mode.")
Com.add_flag("s", "Shutdown PC after script finish.")
Com.add_key("dir", ParametersTypes.ValidPath, "Output directory.")
CommandsList.append(Com)

Com = Command("install", "Install parsers.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_argument(ParametersTypes.Text, "Name of parser.")
ComPos.add_flag("all", "Install all parsers.")
Com.add_flag("f", "Enable force mode.")
Com.add_flag("ssh", "Use SSH mode for repositories cloning.")
CommandsList.append(Com)

Com = Command("list", "Print list of installed parsers.")
Com.add_flag("s", "Shutdown PC after script finish.")
CommandsList.append(Com)

Com = Command("parse", "Start titles parsing.")
ComPos = Com.create_position("TARGET", "Target for parsing.", important = True)
ComPos.add_argument(description = "Title slug.")
ComPos.add_flag("collection", "Parse slugs from Collection.txt file.")
ComPos.add_flag("local", "Parse all locally saved titles.")
ComPos.add_flag("updates", "Parse titles updated for last 24 hours.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Text, "Parser name.")
Com.add_key("period", ParametersTypes.Number, "Period in hours for parsing updates.")
Com.add_key("from", description = "Skip titles before this slug.")
Com.add_flag("f", "Enable force mode.")
Com.add_flag("s", "Shutdown PC after script finish.")
CommandsList.append(Com)

Com = Command("repair", "Repair chapter content in locally saved title.")
ComPos = Com.create_position("FILENAME", "Source file.", important = True)
ComPos.add_argument(description = "Filename of locally saved title.")
ComPos = Com.create_position("TARGET", "Target for repairing.", important = True)
ComPos.add_key("chapter", ParametersTypes.Number, "Chapter ID.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ParametersTypes.Text, "Parser name.")
Com.add_flag("s", "Shutdown PC after script finish.")
CommandsList.append(Com)

Com = Command("run", "Run specific modules.")
ComPos = Com.create_position("TARGET", "Target to run.", important = True)
ComPos.add_key("extension", ParametersTypes.Text, "Extension name.")
ComPos = Com.create_position("PARSER", "Parser for using context.", important = True)
ComPos.add_key("use", ParametersTypes.Text, "Parser name.")
Com.add_key("command", description = "Extension command.")
CommandsList.append(Com)

Com = Command("tagger", "Process titles classificators.")
ComPos = Com.create_position("INPUT", "Input data.", important = True)
ComPos.add_key("classificator", ParametersTypes.All, "Unknown type of classificator.")
ComPos.add_key("genre", ParametersTypes.All, "Genre.")
ComPos.add_key("franchise", ParametersTypes.All, "Franchise.")
ComPos.add_key("tag", ParametersTypes.All, "Tag.")
ComPos = Com.create_position("PARSER", "Parser name to determine source rules.")
ComPos.add_key("use", ParametersTypes.Text, "Parser name.")
ComPos = Com.create_position("OUTPUT", "Output mode.")
ComPos.add_flag("print", "Styled print in console (default).")
ComPos.add_flag("json", "Prints JSON-string in console.")
ComPos.add_key("file", description = "Path to dump JSON file.")
CommandsList.append(Com)

Com = Command("uninstall", "Uninstall parsers.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_argument(ParametersTypes.Text, "Name of parser.")
ComPos.add_flag("all", "Uninstall all parsers.")
Com.add_flag("f", "Also remove configs.")
CommandsList.append(Com)