from dublib.CLI.Terminalyzer import Command, ValidableTypes

COMMANDS: list[Command] = list()

Com = Command("build-manga", "Build readable manga.")
ComPos = Com.create_position("SOURCE", "Filename of local JSON.", important = True)
ComPos.set_argument()
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("--use", type = ValidableTypes.Alpha, description = "Parser name.")
ComPos = Com.create_position("TARGET", "Target for building.")
ComPos.add_key("--branch", type = ValidableTypes.Number, description = "Branch ID.")
ComPos.add_key("--chapter", type = ValidableTypes.Number, description = "Chapter ID.")
ComPos = Com.create_position("BUILDER", "Type of building system.")
ComPos.add_flag("-simple", description = "Download images in directories (default).")
ComPos.add_flag("-zip", description = "Make *.ZIP archives.")
ComPos.add_flag("-cbz", description = "Make *.CBZ files.")
Com.base.add_key("--ch-template", description = "Template for chapters naming. Available {number} and {name} replacements.")
Com.base.add_key("--vol-template", description = "Template for volumes naming. Available {number} replacement.")
Com.base.add_flag("-v", description = "Enable chapters sorting by volumes directories.")
COMMANDS.append(Com)

Com = Command("build-ranobe", "Build readable ranobe.")
ComPos = Com.create_position("SOURCE", "Filename of local JSON.", important = True)
ComPos.set_argument()
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("--use", type = ValidableTypes.Alpha, description = "Parser name.")
ComPos = Com.create_position("TARGET", "Target for building.")
ComPos.add_key("--branch", type = ValidableTypes.Number, description = "Branch ID.")
COMMANDS.append(Com)



Com = Command("init", "Initialize new parser or extension directory for development.")
ComPos = Com.create_position("TYPE", "Type of module.", important = True)
ComPos.add_flag("-e", description = "Extension.")
ComPos.add_flag("-p", description = "Parser.")
ComPos = Com.create_position("NAME", "Parser or extension name.", important = True)
ComPos.set_argument(ValidableTypes.All)
ComPos = Com.create_position("CONTENT", "Parser content types.")
ComPos.add_key("--content", description = "Parser content types. For example \"manga,ranobe\".")
Com.base.add_flag("-f", description = "Enable force mode.")
Com.base.add_flag("-git", description = "Initialize new Git repository.")
COMMANDS.append(Com)

Com = Command("parse", "Start titles parsing.")
ComPos = Com.create_position("TARGET", "Target for parsing.", important = True)
ComPos.add_argument(description = "Title slug.")
ComPos.add_key("id", ValidableTypes.Number, "Title ID for searching slug in local files.")
ComPos.add_flag("collection", "Parse slugs from Collection.txt file.")
ComPos.add_flag("local", "Parse all locally saved titles.")
ComPos.add_flag("updates", "Parse titles updated for last 24 hours.")
ComPos.add_flag("last", "Parse last processed slug.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ValidableTypes.Alpha, "Parser name.")
Com.base.add_key("period", ValidableTypes.Number, "Period in hours for parsing. Use with -updates flag.")
Com.base.add_key("from", description = "Skip titles before this slug.")
Com.base.add_flag("f", "Enable force mode.")
Com.base.add_flag("sort", "Enable chapters sorting after parsing.")
Com.base.add_flag("no-amend", "Disable chapters content amending.")
COMMANDS.append(Com)

Com = Command("repair", "Repair chapter content in locally saved title.")
ComPos = Com.create_position("FILENAME", "Source file.", important = True)
ComPos.add_argument(description = "Filename of locally saved title.")
ComPos = Com.create_position("TARGET", "Target for repairing.", important = True)
ComPos.add_key("chapter", ValidableTypes.Number, "Chapter ID.")
ComPos = Com.create_position("PARSER", "Name of parser.", important = True)
ComPos.add_key("use", ValidableTypes.Alpha, "Parser name.")
COMMANDS.append(Com)